# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: example

  app:
    container_name: warehouse-api
    image: warehouse-api
    command:
      [
        './wait-for-it.sh',
        'postgres:5432',
        '--timeout=${POSTGRES_APP_WAIT_TIMEOUT}',
        '--',
        'npm',
        'run',
        'start',
      ]
    restart: always
    ports:
      - 3000:3000
      - 9231:9231

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
