# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: example
    ports:
      - '5438:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
